// Auto generated by Craby. DO NOT EDIT.
#include <CxxCrabyModuleTestModule.hpp>
#include <ReactCommon/CxxTurboModuleUtils.h>
#include <jni.h>

jint JNI_OnLoad(JavaVM *vm, void *reserved) {
  facebook::react::registerCxxModuleToGlobalModuleMap(
    craby::crabymoduletest::modules::CxxCrabyModuleTestModule::kModuleName,
    [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::crabymoduletest::modules::CxxCrabyModuleTestModule>(jsInvoker);
    });
  return JNI_VERSION_1_6;
}

extern "C"
JNIEXPORT void JNICALL
Java_rs_craby_crabymoduletest_CrabyModuleTestPackage_nativeSetDataPath(JNIEnv *env, jclass clazz, jstring jDataPath) {
  const char* cDataPath = env->GetStringUTFChars(jDataPath, nullptr);
  auto dataPath = std::string(cDataPath);
  env->ReleaseStringUTFChars(jDataPath, cDataPath);
  craby::crabymoduletest::modules::CxxCrabyModuleTestModule::dataPath = dataPath;
}
