// Auto generated by Craby. DO NOT EDIT.
#include "CxxCrabyModuleTestModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace crabymoduletest {
namespace modules {

std::string CxxCrabyModuleTestModule::dataPath = std::string();

CxxCrabyModuleTestModule::CxxCrabyModuleTestModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxCrabyModuleTestModule::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::crabymoduletest::bridging::CrabyModuleTest>(
    craby::crabymoduletest::bridging::createCrabyModuleTest(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::crabymoduletest::bridging::CrabyModuleTest *ptr) { rust::Box<craby::crabymoduletest::bridging::CrabyModuleTest>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::crabymoduletest::utils::ThreadPool>(10);
  methodMap_["add"] = MethodMetadata{2, &CxxCrabyModuleTestModule::add};
  methodMap_["divide"] = MethodMetadata{2, &CxxCrabyModuleTestModule::divide};
  methodMap_["multiply"] = MethodMetadata{2, &CxxCrabyModuleTestModule::multiply};
  methodMap_["subtract"] = MethodMetadata{2, &CxxCrabyModuleTestModule::subtract};
}

CxxCrabyModuleTestModule::~CxxCrabyModuleTestModule() {
  invalidate();
}

void CxxCrabyModuleTestModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxCrabyModuleTestModule::add(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCrabyModuleTestModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::crabymoduletest::bridging::add(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::crabymoduletest::utils::errorMessage(err));
  }
}

jsi::Value CxxCrabyModuleTestModule::divide(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCrabyModuleTestModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::crabymoduletest::bridging::divide(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::crabymoduletest::utils::errorMessage(err));
  }
}

jsi::Value CxxCrabyModuleTestModule::multiply(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCrabyModuleTestModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::crabymoduletest::bridging::multiply(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::crabymoduletest::utils::errorMessage(err));
  }
}

jsi::Value CxxCrabyModuleTestModule::subtract(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCrabyModuleTestModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::crabymoduletest::bridging::subtract(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::crabymoduletest::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace crabymoduletest
} // namespace craby
