// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::craby_module_test_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::crabymoduletest::bridging")]
pub mod bridging {
    extern "Rust" {
        type CrabyModuleTest;

        #[cxx_name = "createCrabyModuleTest"]
        fn create_craby_module_test(id: usize, data_path: &str) -> Box<CrabyModuleTest>;

        #[cxx_name = "add"]
        fn craby_module_test_add(it_: &mut CrabyModuleTest, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "divide"]
        fn craby_module_test_divide(it_: &mut CrabyModuleTest, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "multiply"]
        fn craby_module_test_multiply(it_: &mut CrabyModuleTest, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "subtract"]
        fn craby_module_test_subtract(it_: &mut CrabyModuleTest, a: f64, b: f64) -> Result<f64>;
    }
}

fn create_craby_module_test(id: usize, data_path: &str) -> Box<CrabyModuleTest> {
    let ctx = Context::new(id, data_path);
    Box::new(CrabyModuleTest::new(ctx))
}

fn craby_module_test_add(it_: &mut CrabyModuleTest, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.add(a, b);
        ret
    })
}

fn craby_module_test_divide(it_: &mut CrabyModuleTest, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.divide(a, b);
        ret
    })
}

fn craby_module_test_multiply(it_: &mut CrabyModuleTest, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.multiply(a, b);
        ret
    })
}

fn craby_module_test_subtract(it_: &mut CrabyModuleTest, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.subtract(a, b);
        ret
    })
}


